/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId/settings'
import { Route as ProjectIdNodeSubGraphNodeRefRouteImport } from './routes/$projectId/node-sub-graph/$nodeRef'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdNodeSubGraphNodeRefRoute =
  ProjectIdNodeSubGraphNodeRefRouteImport.update({
    id: '/node-sub-graph/$nodeRef',
    path: '/node-sub-graph/$nodeRef',
    getParentRoute: () => ProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/$projectId/settings'
    | '/$projectId/'
    | '/$projectId/node-sub-graph/$nodeRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId/settings'
    | '/$projectId'
    | '/$projectId/node-sub-graph/$nodeRef'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/$projectId/settings'
    | '/$projectId/'
    | '/$projectId/node-sub-graph/$nodeRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/node-sub-graph/$nodeRef': {
      id: '/$projectId/node-sub-graph/$nodeRef'
      path: '/node-sub-graph/$nodeRef'
      fullPath: '/$projectId/node-sub-graph/$nodeRef'
      preLoaderRoute: typeof ProjectIdNodeSubGraphNodeRefRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdNodeSubGraphNodeRefRoute: typeof ProjectIdNodeSubGraphNodeRefRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdNodeSubGraphNodeRefRoute: ProjectIdNodeSubGraphNodeRefRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
