/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdViewRouteImport } from './routes/$projectId/view'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId/settings'
import { Route as ProjectIdViewModulesGraphRouteImport } from './routes/$projectId/view/modules-graph'
import { Route as ProjectIdViewModulesDotRouteImport } from './routes/$projectId/view/modules-dot'
import { Route as ProjectIdViewFullGraphRouteImport } from './routes/$projectId/view/full-graph'
import { Route as ProjectIdViewFullDotRouteImport } from './routes/$projectId/view/full-dot'
import { Route as ProjectIdViewFlowRouteImport } from './routes/$projectId/view/flow'
import { Route as ProjectIdNodeSubGraphNodeRefRouteImport } from './routes/$projectId/node-sub-graph/$nodeRef'
import { Route as ProjectIdNodeDetailsNodeRefRouteImport } from './routes/$projectId/node-details/$nodeRef'
import { Route as ProjectIdNodeDebugDetailsNodeRefRouteImport } from './routes/$projectId/node-debug-details/$nodeRef'
import { Route as ProjectIdModuleSubGraphModuleNameRouteImport } from './routes/$projectId/module-sub-graph/$moduleName'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdViewRoute = ProjectIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdViewModulesGraphRoute =
  ProjectIdViewModulesGraphRouteImport.update({
    id: '/modules-graph',
    path: '/modules-graph',
    getParentRoute: () => ProjectIdViewRoute,
  } as any)
const ProjectIdViewModulesDotRoute = ProjectIdViewModulesDotRouteImport.update({
  id: '/modules-dot',
  path: '/modules-dot',
  getParentRoute: () => ProjectIdViewRoute,
} as any)
const ProjectIdViewFullGraphRoute = ProjectIdViewFullGraphRouteImport.update({
  id: '/full-graph',
  path: '/full-graph',
  getParentRoute: () => ProjectIdViewRoute,
} as any)
const ProjectIdViewFullDotRoute = ProjectIdViewFullDotRouteImport.update({
  id: '/full-dot',
  path: '/full-dot',
  getParentRoute: () => ProjectIdViewRoute,
} as any)
const ProjectIdViewFlowRoute = ProjectIdViewFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => ProjectIdViewRoute,
} as any)
const ProjectIdNodeSubGraphNodeRefRoute =
  ProjectIdNodeSubGraphNodeRefRouteImport.update({
    id: '/node-sub-graph/$nodeRef',
    path: '/node-sub-graph/$nodeRef',
    getParentRoute: () => ProjectIdRoute,
  } as any)
const ProjectIdNodeDetailsNodeRefRoute =
  ProjectIdNodeDetailsNodeRefRouteImport.update({
    id: '/node-details/$nodeRef',
    path: '/node-details/$nodeRef',
    getParentRoute: () => ProjectIdRoute,
  } as any)
const ProjectIdNodeDebugDetailsNodeRefRoute =
  ProjectIdNodeDebugDetailsNodeRefRouteImport.update({
    id: '/node-debug-details/$nodeRef',
    path: '/node-debug-details/$nodeRef',
    getParentRoute: () => ProjectIdRoute,
  } as any)
const ProjectIdModuleSubGraphModuleNameRoute =
  ProjectIdModuleSubGraphModuleNameRouteImport.update({
    id: '/module-sub-graph/$moduleName',
    path: '/module-sub-graph/$moduleName',
    getParentRoute: () => ProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId/view': typeof ProjectIdViewRouteWithChildren
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/module-sub-graph/$moduleName': typeof ProjectIdModuleSubGraphModuleNameRoute
  '/$projectId/node-debug-details/$nodeRef': typeof ProjectIdNodeDebugDetailsNodeRefRoute
  '/$projectId/node-details/$nodeRef': typeof ProjectIdNodeDetailsNodeRefRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
  '/$projectId/view/flow': typeof ProjectIdViewFlowRoute
  '/$projectId/view/full-dot': typeof ProjectIdViewFullDotRoute
  '/$projectId/view/full-graph': typeof ProjectIdViewFullGraphRoute
  '/$projectId/view/modules-dot': typeof ProjectIdViewModulesDotRoute
  '/$projectId/view/modules-graph': typeof ProjectIdViewModulesGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId/view': typeof ProjectIdViewRouteWithChildren
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/module-sub-graph/$moduleName': typeof ProjectIdModuleSubGraphModuleNameRoute
  '/$projectId/node-debug-details/$nodeRef': typeof ProjectIdNodeDebugDetailsNodeRefRoute
  '/$projectId/node-details/$nodeRef': typeof ProjectIdNodeDetailsNodeRefRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
  '/$projectId/view/flow': typeof ProjectIdViewFlowRoute
  '/$projectId/view/full-dot': typeof ProjectIdViewFullDotRoute
  '/$projectId/view/full-graph': typeof ProjectIdViewFullGraphRoute
  '/$projectId/view/modules-dot': typeof ProjectIdViewModulesDotRoute
  '/$projectId/view/modules-graph': typeof ProjectIdViewModulesGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/$projectId/view': typeof ProjectIdViewRouteWithChildren
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/module-sub-graph/$moduleName': typeof ProjectIdModuleSubGraphModuleNameRoute
  '/$projectId/node-debug-details/$nodeRef': typeof ProjectIdNodeDebugDetailsNodeRefRoute
  '/$projectId/node-details/$nodeRef': typeof ProjectIdNodeDetailsNodeRefRoute
  '/$projectId/node-sub-graph/$nodeRef': typeof ProjectIdNodeSubGraphNodeRefRoute
  '/$projectId/view/flow': typeof ProjectIdViewFlowRoute
  '/$projectId/view/full-dot': typeof ProjectIdViewFullDotRoute
  '/$projectId/view/full-graph': typeof ProjectIdViewFullGraphRoute
  '/$projectId/view/modules-dot': typeof ProjectIdViewModulesDotRoute
  '/$projectId/view/modules-graph': typeof ProjectIdViewModulesGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/$projectId/settings'
    | '/$projectId/view'
    | '/$projectId/'
    | '/$projectId/module-sub-graph/$moduleName'
    | '/$projectId/node-debug-details/$nodeRef'
    | '/$projectId/node-details/$nodeRef'
    | '/$projectId/node-sub-graph/$nodeRef'
    | '/$projectId/view/flow'
    | '/$projectId/view/full-dot'
    | '/$projectId/view/full-graph'
    | '/$projectId/view/modules-dot'
    | '/$projectId/view/modules-graph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId/settings'
    | '/$projectId/view'
    | '/$projectId'
    | '/$projectId/module-sub-graph/$moduleName'
    | '/$projectId/node-debug-details/$nodeRef'
    | '/$projectId/node-details/$nodeRef'
    | '/$projectId/node-sub-graph/$nodeRef'
    | '/$projectId/view/flow'
    | '/$projectId/view/full-dot'
    | '/$projectId/view/full-graph'
    | '/$projectId/view/modules-dot'
    | '/$projectId/view/modules-graph'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/$projectId/settings'
    | '/$projectId/view'
    | '/$projectId/'
    | '/$projectId/module-sub-graph/$moduleName'
    | '/$projectId/node-debug-details/$nodeRef'
    | '/$projectId/node-details/$nodeRef'
    | '/$projectId/node-sub-graph/$nodeRef'
    | '/$projectId/view/flow'
    | '/$projectId/view/full-dot'
    | '/$projectId/view/full-graph'
    | '/$projectId/view/modules-dot'
    | '/$projectId/view/modules-graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/view': {
      id: '/$projectId/view'
      path: '/view'
      fullPath: '/$projectId/view'
      preLoaderRoute: typeof ProjectIdViewRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/view/modules-graph': {
      id: '/$projectId/view/modules-graph'
      path: '/modules-graph'
      fullPath: '/$projectId/view/modules-graph'
      preLoaderRoute: typeof ProjectIdViewModulesGraphRouteImport
      parentRoute: typeof ProjectIdViewRoute
    }
    '/$projectId/view/modules-dot': {
      id: '/$projectId/view/modules-dot'
      path: '/modules-dot'
      fullPath: '/$projectId/view/modules-dot'
      preLoaderRoute: typeof ProjectIdViewModulesDotRouteImport
      parentRoute: typeof ProjectIdViewRoute
    }
    '/$projectId/view/full-graph': {
      id: '/$projectId/view/full-graph'
      path: '/full-graph'
      fullPath: '/$projectId/view/full-graph'
      preLoaderRoute: typeof ProjectIdViewFullGraphRouteImport
      parentRoute: typeof ProjectIdViewRoute
    }
    '/$projectId/view/full-dot': {
      id: '/$projectId/view/full-dot'
      path: '/full-dot'
      fullPath: '/$projectId/view/full-dot'
      preLoaderRoute: typeof ProjectIdViewFullDotRouteImport
      parentRoute: typeof ProjectIdViewRoute
    }
    '/$projectId/view/flow': {
      id: '/$projectId/view/flow'
      path: '/flow'
      fullPath: '/$projectId/view/flow'
      preLoaderRoute: typeof ProjectIdViewFlowRouteImport
      parentRoute: typeof ProjectIdViewRoute
    }
    '/$projectId/node-sub-graph/$nodeRef': {
      id: '/$projectId/node-sub-graph/$nodeRef'
      path: '/node-sub-graph/$nodeRef'
      fullPath: '/$projectId/node-sub-graph/$nodeRef'
      preLoaderRoute: typeof ProjectIdNodeSubGraphNodeRefRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/node-details/$nodeRef': {
      id: '/$projectId/node-details/$nodeRef'
      path: '/node-details/$nodeRef'
      fullPath: '/$projectId/node-details/$nodeRef'
      preLoaderRoute: typeof ProjectIdNodeDetailsNodeRefRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/node-debug-details/$nodeRef': {
      id: '/$projectId/node-debug-details/$nodeRef'
      path: '/node-debug-details/$nodeRef'
      fullPath: '/$projectId/node-debug-details/$nodeRef'
      preLoaderRoute: typeof ProjectIdNodeDebugDetailsNodeRefRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/module-sub-graph/$moduleName': {
      id: '/$projectId/module-sub-graph/$moduleName'
      path: '/module-sub-graph/$moduleName'
      fullPath: '/$projectId/module-sub-graph/$moduleName'
      preLoaderRoute: typeof ProjectIdModuleSubGraphModuleNameRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdViewRouteChildren {
  ProjectIdViewFlowRoute: typeof ProjectIdViewFlowRoute
  ProjectIdViewFullDotRoute: typeof ProjectIdViewFullDotRoute
  ProjectIdViewFullGraphRoute: typeof ProjectIdViewFullGraphRoute
  ProjectIdViewModulesDotRoute: typeof ProjectIdViewModulesDotRoute
  ProjectIdViewModulesGraphRoute: typeof ProjectIdViewModulesGraphRoute
}

const ProjectIdViewRouteChildren: ProjectIdViewRouteChildren = {
  ProjectIdViewFlowRoute: ProjectIdViewFlowRoute,
  ProjectIdViewFullDotRoute: ProjectIdViewFullDotRoute,
  ProjectIdViewFullGraphRoute: ProjectIdViewFullGraphRoute,
  ProjectIdViewModulesDotRoute: ProjectIdViewModulesDotRoute,
  ProjectIdViewModulesGraphRoute: ProjectIdViewModulesGraphRoute,
}

const ProjectIdViewRouteWithChildren = ProjectIdViewRoute._addFileChildren(
  ProjectIdViewRouteChildren,
)

interface ProjectIdRouteChildren {
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ProjectIdViewRoute: typeof ProjectIdViewRouteWithChildren
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdModuleSubGraphModuleNameRoute: typeof ProjectIdModuleSubGraphModuleNameRoute
  ProjectIdNodeDebugDetailsNodeRefRoute: typeof ProjectIdNodeDebugDetailsNodeRefRoute
  ProjectIdNodeDetailsNodeRefRoute: typeof ProjectIdNodeDetailsNodeRefRoute
  ProjectIdNodeSubGraphNodeRefRoute: typeof ProjectIdNodeSubGraphNodeRefRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ProjectIdViewRoute: ProjectIdViewRouteWithChildren,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdModuleSubGraphModuleNameRoute:
    ProjectIdModuleSubGraphModuleNameRoute,
  ProjectIdNodeDebugDetailsNodeRefRoute: ProjectIdNodeDebugDetailsNodeRefRoute,
  ProjectIdNodeDetailsNodeRefRoute: ProjectIdNodeDetailsNodeRefRoute,
  ProjectIdNodeSubGraphNodeRefRoute: ProjectIdNodeSubGraphNodeRefRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
